FROM node:20.11.1-alpine3.19

ENV NODE_ENV=development
ENV PORT=3000

WORKDIR "/app"

COPY ./package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN npm run prisma:generate

CMD [ "npm", "run", "dev" ]