version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    container_name: api
    depends_on:
      - postgres
    restart: always
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 443:443
